var riot = require("riot")

require('./components/router.tag')
require('./components/macaroon.tag')
require('./components/only-logo.tag')
require('./components/topnav.tag')
require('./components/modal.tag')
require('./components/signuporsignin.tag')
require('./components/job.tag')
require('./components/control.tag')
require('./components/app.tag')
require('./components/poller.tag')
require('./components/homepage.tag')
require('./components/drafteditpage.tag')
require('./components/anon_homepage.tag')
require('./components/loggedin_homepage.tag')
require('./components/login.tag')
require('./components/tsform.tag')

riot.mount('#app', 'app')
