var riot = require("riot")
require('./components/router.tag')
require('./components/job.tag')
require('./components/control.tag')
require('./components/app.tag')
require('./components/homepage.tag')
require('./components/drafteditpage.tag')
require('./components/anon_homepage.tag')
require('./components/loggedin_homepage.tag')
require('./components/login.tag')
// riot.mount('*')
riot.mount('app')
